import type { SystemState } from "./types";

/** Fresh copy per call - never share mutable seed objects across resets */
export function seedState(): SystemState{
    return {
        incident:{
            id: "INC-1847",
            title:"Checkout success rate degraded",
            status:"active",
            startedMinutesAgo: 8,
            affectedServiceIds: ["checkout-api", "payment-service"],
            resolutionSummary: null,
        },
        services: [
            {
                id: "checkout-api",
                name: "Checkout API",
                status: "degraded",
                current:  { successRate: 0.61,  errorRate: 0.39,  p95Ms: 820 },
                baseline: { successRate: 0.994, errorRate: 0.006, p95Ms: 240 },
            },
            {
                id: "payment-service",
                name: "Payment Service",
                status: "down",
                current:  { successRate: 0.18,  errorRate: 0.82,  p95Ms: 5200 },
                baseline: { successRate: 0.998, errorRate: 0.002, p95Ms: 640 }, // 8.1x
            },
            {
                id: "auth-service",
                name: "Auth Service",
                status: "healthy",
                current:  { successRate: 0.999, errorRate: 0.001, p95Ms: 118 },
                baseline: { successRate: 0.999, errorRate: 0.001, p95Ms: 120 },
            },
            {
                id: "search-service",
                name: "Search Service",
                status: "healthy",
                current:  { successRate: 0.997, errorRate: 0.003, p95Ms: 310 },
                baseline: { successRate: 0.997, errorRate: 0.003, p95Ms: 305 },
            },
            {
                id: "database",
                name: "Primary Database",
                status: "healthy",
                current:  { successRate: 1.0, errorRate: 0.0, p95Ms: 35 },
                baseline: { successRate: 1.0, errorRate: 0.0, p95Ms: 33 },
            },
        ],
        deployments:[
            {
                id: "deploy-184",
                serviceId: "payment-service",
                version: "v4.2.0",
                previousVersion: "v4.1.3",
                deployedMinutesAgo: 10,
                author: "m.okafor",
                summary: "Add retry logic to gateway client; raise connection pool timeout to 500ms",
                status: "active",
            },{
                id: "deploy-186",
                serviceId: "auth-service",
                version: "v2.7.1",
                previousVersion: "v2.7.0",
                deployedMinutesAgo: 6,
                author: "s.lindqvist",
                summary: "Bump session cookie max-age",
                status: "active",
            }, {
                id: "deploy-183",
                serviceId: "payment-service",
                version: "v4.1.3",
                previousVersion: "v4.1.2",
                deployedMinutesAgo: 155,
                author: "m.okafor",
                summary: "Structured logging for gateway responses",
                status: "superseded",
            }, {
                id: "deploy-182",
                serviceId: "payment-service",
                version: "v4.1.2",
                previousVersion: "v4.1.1",
                deployedMinutesAgo: 320,
                author: "d.reyes",
                summary: "Dependency bump",
                status: "superseded",
            }, 
        ],
        dependencies: [
            { from: "checkout-api",    to: "payment-service", callsPerMin: 1240 },
            { from: "checkout-api",    to: "auth-service",    callsPerMin: 1240 },
            { from: "checkout-api",    to: "database",        callsPerMin: 3100 },
            { from: "payment-service", to: "database",        callsPerMin: 980 },
            { from: "search-service",  to: "database",        callsPerMin: 450 },
        ],
        logs: [
            { id: "log-001", serviceId: "payment-service", atMinutesAgo: 8, level: "ERROR",
                message: "Connection timeout to payment gateway after 5000ms", traceId: "tr-9f2a" },
            { id: "log-002", serviceId: "payment-service", atMinutesAgo: 8, level: "ERROR",
                message: "Retry 3/3 exhausted for gateway request", traceId: "tr-9f2a" },
            { id: "log-003", serviceId: "checkout-api", atMinutesAgo: 8, level: "ERROR",
                message: "PaymentServiceUnavailable: upstream returned 503", traceId: "tr-9f2a" },
            { id: "log-004", serviceId: "payment-service", atMinutesAgo: 10, level: "INFO",
                message: "Deployment v4.2.0 completed, connection pool timeout=5000ms" },
            { id: "log-005", serviceId: "checkout-api", atMinutesAgo: 7, level: "WARN",
                message: "Checkout p95 latency exceeded 800ms SLO" },
            { id: "log-006", serviceId: "auth-service", atMinutesAgo: 6, level: "INFO",
                message: "Deployment v2.7.1 completed, 0 errors in smoke test" },
            { id: "log-007", serviceId: "payment-service", atMinutesAgo: 11, level: "INFO",
                message: "Health check passing, p95=640ms" },
        ],
        findings: [],
        toolCalls: [],
        plans: [],
        focusedServiceId: null,
        logFilter: null,
        webmcp: {available: false, registered: []},
    };
}